import { PrismaClient, PlanType } from '@prisma/client';

const prisma = new PrismaClient({
  log: ['error', 'warn'],
});

async function main() {
  console.log('Starting seed...');

  try {
    console.log('Clearing existing data...');
    await prisma.pensionPlan.deleteMany();

    const federalPlans = [
      {
        name: 'Public Service Pension Plan (PSPP)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for federal public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Public Service',
        membershipSize: 320000,
        fundSize: 170000000000,
        fundingStatus: 1.08,
        investmentOptions: [],
        websiteUrl: 'https://www.canada.ca/en/treasury-board-secretariat/topics/pension-benefits.html',
        contactInfo: 'Government of Canada Pension Centre',
        lastUpdated: new Date(),
        sources: ['Treasury Board of Canada']
      },

      // Military and Defense
      {
        name: 'Canadian Forces Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for regular force members of the Canadian Armed Forces',
        accrualRate: 0.02,
        retirementAge: 60,
        earlyRetirementAge: 50,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Military',
        membershipSize: 95000,
        fundSize: 55000000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.canada.ca/en/department-national-defence/services/benefits-military/pension-benefits.html',
        contactInfo: 'CAF Pension Services',
        lastUpdated: new Date(),
        sources: ['Department of National Defence']
      },
      {
        name: 'Reserve Force Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for members of the Canadian Forces Reserve',
        accrualRate: 0.02,
        retirementAge: 60,
        earlyRetirementAge: 50,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Military',
        membershipSize: 27000,
        fundSize: 750000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.canada.ca/en/department-national-defence/services/benefits-military/pension-benefits/reserve.html',
        contactInfo: 'Reserve Force Pension Services',
        lastUpdated: new Date(),
        sources: ['Department of National Defence']
      },

      // Law Enforcement
      {
        name: 'Royal Canadian Mounted Police Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for members of the RCMP',
        accrualRate: 0.02,
        retirementAge: 60,
        earlyRetirementAge: 50,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Law Enforcement',
        membershipSize: 40000,
        fundSize: 13000000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.rcmp-grc.gc.ca/en/pension-benefits',
        contactInfo: 'RCMP Pension Services',
        lastUpdated: new Date(),
        sources: ['RCMP']
      },

      // Crown Corporations
      {
        name: 'Canada Post Corporation Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Canada Post employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Crown Corporation',
        membershipSize: 64000,
        fundSize: 27000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.canadapost.ca/cpc/en/our-company/about-us/pension-plan.page',
        contactInfo: 'Canada Post Pension Centre',
        lastUpdated: new Date(),
        sources: ['Canada Post Annual Report']
      },
      {
        name: 'CBC/Radio-Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for CBC/Radio-Canada employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Crown Corporation',
        membershipSize: 8500,
        fundSize: 8000000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.cbc.radio-canada.ca/en/working-with-us/retirement',
        contactInfo: 'CBC Pension Administration Centre',
        lastUpdated: new Date(),
        sources: ['CBC/Radio-Canada Annual Report']
      },
      {
        name: 'Bank of Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Bank of Canada employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Crown Corporation',
        membershipSize: 4500,
        fundSize: 2000000000,
        fundingStatus: 1.06,
        investmentOptions: [],
        websiteUrl: 'https://www.bankofcanada.ca/careers/pension-benefits/',
        contactInfo: 'Bank of Canada Pension Services',
        lastUpdated: new Date(),
        sources: ['Bank of Canada Annual Report']
      },
      {
        name: 'VIA Rail Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for VIA Rail employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Crown Corporation',
        membershipSize: 3000,
        fundSize: 2500000000,
        fundingStatus: 0.96,
        investmentOptions: [],
        websiteUrl: 'https://www.viarail.ca/en/about-via-rail/careers/benefits',
        contactInfo: 'VIA Rail Pension Services',
        lastUpdated: new Date(),
        sources: ['VIA Rail Annual Report']
      },

      // Federal Agencies
      {
        name: 'National Research Council Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for NRC employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Research',
        membershipSize: 4200,
        fundSize: 3500000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://nrc.canada.ca/en/careers/benefits',
        contactInfo: 'NRC Pension Services',
        lastUpdated: new Date(),
        sources: ['National Research Council']
      },
      {
        name: 'Canadian Nuclear Laboratories Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for CNL employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Energy',
        membershipSize: 3500,
        fundSize: 3000000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.cnl.ca/careers/benefits/',
        contactInfo: 'CNL Pension Administration',
        lastUpdated: new Date(),
        sources: ['Canadian Nuclear Laboratories']
      }
    ];

    const provincialPlans = [
      // Ontario
      {
        name: 'Ontario Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Ontario teachers and education workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Education',
        membershipSize: 330000,
        fundSize: 220000000000,
        fundingStatus: 1.13,
        investmentOptions: [],
        websiteUrl: 'https://www.otpp.com',
        contactInfo: 'OTPP Member Services',
        lastUpdated: new Date(),
        sources: ['OTPP Annual Report']
      },
      {
        name: 'Healthcare of Ontario Pension Plan (HOOPP)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Ontario healthcare workers',
        accrualRate: 0.0175,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Healthcare',
        membershipSize: 400000,
        fundSize: 104000000000,
        fundingStatus: 1.11,
        investmentOptions: [],
        websiteUrl: 'https://hoopp.com',
        contactInfo: 'HOOPP Client Services',
        lastUpdated: new Date(),
        sources: ['HOOPP Annual Report']
      },
      {
        name: 'OPTrust (Ontario Public Service Employees Union Pension Plan)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Ontario public service employees and OPSEU members',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Public Service',
        membershipSize: 95000,
        fundSize: 25000000000,
        fundingStatus: 1.09,
        investmentOptions: [],
        websiteUrl: 'https://www.optrust.com',
        contactInfo: 'OPTrust Member Services',
        lastUpdated: new Date(),
        sources: ['OPTrust Annual Report']
      },

      // British Columbia
      {
        name: 'British Columbia Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for BC teachers and education workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'British Columbia',
        sector: 'Education',
        membershipSize: 98000,
        fundSize: 33200000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://tpp.pensionsbc.ca',
        contactInfo: 'Teachers\' Pension Plan',
        lastUpdated: new Date(),
        sources: ['BC Teachers\' Pension Plan']
      },
      {
        name: 'British Columbia Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for BC public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'British Columbia',
        sector: 'Public Service',
        membershipSize: 135000,
        fundSize: 37000000000,
        fundingStatus: 1.07,
        investmentOptions: [],
        websiteUrl: 'https://pspp.pensionsbc.ca',
        contactInfo: 'Public Service Pension Plan of BC',
        lastUpdated: new Date(),
        sources: ['BC Public Service Pension Plan']
      },
      {
        name: 'British Columbia Municipal Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for BC municipal employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'British Columbia',
        sector: 'Municipal',
        membershipSize: 205000,
        fundSize: 45000000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://mpp.pensionsbc.ca',
        contactInfo: 'Municipal Pension Plan of BC',
        lastUpdated: new Date(),
        sources: ['BC Municipal Pension Plan']
      },

      // Alberta
      {
        name: 'Alberta Teachers\' Retirement Fund',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Alberta teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Alberta',
        sector: 'Education',
        membershipSize: 84000,
        fundSize: 20500000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.atrf.com',
        contactInfo: 'ATRF Member Services',
        lastUpdated: new Date(),
        sources: ['Alberta Teachers\' Retirement Fund']
      },
      {
        name: 'Local Authorities Pension Plan (Alberta)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Alberta local government and health care employees',
        accrualRate: 0.0185,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Alberta',
        sector: 'Public Service',
        membershipSize: 275000,
        fundSize: 53000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.lapp.ca',
        contactInfo: 'LAPP Member Services',
        lastUpdated: new Date(),
        sources: ['Local Authorities Pension Plan']
      },

      // Quebec
      {
        name: 'RREGOP (Quebec Government and Public Employees Retirement Plan)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Main pension plan for Quebec public sector employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: false, // Quebec has QPP instead
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Public Service',
        membershipSize: 580000,
        fundSize: 76500000000,
        fundingStatus: 1.06,
        investmentOptions: [],
        websiteUrl: 'https://www.retraitequebec.gouv.qc.ca',
        contactInfo: 'Retraite Québec',
        lastUpdated: new Date(),
        sources: ['Retraite Québec']
      },
      {
        name: 'Teachers Pension Plan (Quebec)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Quebec teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: false,
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Education',
        membershipSize: 220000,
        fundSize: 42000000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.retraitequebec.gouv.qc.ca',
        contactInfo: 'Retraite Québec',
        lastUpdated: new Date(),
        sources: ['Retraite Québec']
      },
      // Manitoba
      {
        name: 'Civil Service Superannuation Plan (Manitoba)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Manitoba public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Manitoba',
        sector: 'Public Service',
        membershipSize: 54000,
        fundSize: 8500000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.cssb.mb.ca',
        contactInfo: 'Civil Service Superannuation Board',
        lastUpdated: new Date(),
        sources: ['Manitoba CSSB']
      },
      {
        name: 'Healthcare Employees Pension Plan - Manitoba',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Manitoba healthcare workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Manitoba',
        sector: 'Healthcare',
        membershipSize: 80000,
        fundSize: 9200000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.hepp.mb.ca',
        contactInfo: 'HEPP Member Services',
        lastUpdated: new Date(),
        sources: ['HEPP Annual Report']
      },

      // Saskatchewan
      {
        name: 'Saskatchewan Healthcare Employees\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Saskatchewan healthcare workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Saskatchewan',
        sector: 'Healthcare',
        membershipSize: 60000,
        fundSize: 8100000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.shepp.ca',
        contactInfo: 'SHEPP Member Services',
        lastUpdated: new Date(),
        sources: ['SHEPP Annual Report']
      },
      {
        name: 'Saskatchewan Teachers\' Retirement Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Saskatchewan teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Saskatchewan',
        sector: 'Education',
        membershipSize: 42000,
        fundSize: 6500000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.stf.sk.ca/pension',
        contactInfo: 'Saskatchewan Teachers\' Federation',
        lastUpdated: new Date(),
        sources: ['Saskatchewan Teachers\' Federation']
      },

      // Nova Scotia
      {
        name: 'Nova Scotia Public Service Superannuation Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Nova Scotia public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Nova Scotia',
        sector: 'Public Service',
        membershipSize: 38000,
        fundSize: 6800000000,
        fundingStatus: 0.98,
        investmentOptions: [],
        websiteUrl: 'https://www.nspssp.ca',
        contactInfo: 'NS Pension Services Corporation',
        lastUpdated: new Date(),
        sources: ['Nova Scotia Pension Services Corporation']
      },
      {
        name: 'Nova Scotia Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Nova Scotia teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Nova Scotia',
        sector: 'Education',
        membershipSize: 32000,
        fundSize: 5200000000,
        fundingStatus: 0.97,
        investmentOptions: [],
        websiteUrl: 'https://www.nstpp.ca',
        contactInfo: 'NS Teachers\' Pension Plan',
        lastUpdated: new Date(),
        sources: ['Nova Scotia Teachers\' Pension Plan']
      },

      // New Brunswick
      {
        name: 'New Brunswick Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for New Brunswick public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'New Brunswick',
        sector: 'Public Service',
        membershipSize: 40000,
        fundSize: 7300000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.vestcor.org/nbpspp',
        contactInfo: 'Vestcor Pension Services',
        lastUpdated: new Date(),
        sources: ['Vestcor Annual Report']
      },
      {
        name: 'New Brunswick Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for New Brunswick teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'New Brunswick',
        sector: 'Education',
        membershipSize: 20000,
        fundSize: 6100000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.vestcor.org/nbtpp',
        contactInfo: 'Vestcor Pension Services',
        lastUpdated: new Date(),
        sources: ['Vestcor Annual Report']
      },
      // Prince Edward Island
      {
        name: 'Prince Edward Island Civil Service Superannuation Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for PEI public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Prince Edward Island',
        sector: 'Public Service',
        membershipSize: 8000,
        fundSize: 1800000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.peicssf.ca',
        contactInfo: 'PEI Civil Service Superannuation Fund',
        lastUpdated: new Date(),
        sources: ['PEI Public Sector Pensions']
      },
      {
        name: 'Prince Edward Island Teachers\' Superannuation Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for PEI teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Prince Edward Island',
        sector: 'Education',
        membershipSize: 3500,
        fundSize: 950000000,
        fundingStatus: 0.99,
        investmentOptions: [],
        websiteUrl: 'https://www.peitpp.ca',
        contactInfo: 'PEI Teachers\' Superannuation Commission',
        lastUpdated: new Date(),
        sources: ['PEI Teachers\' Federation']
      },

      // Newfoundland and Labrador
      {
        name: 'Newfoundland and Labrador Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for NL public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Newfoundland and Labrador',
        sector: 'Public Service',
        membershipSize: 27000,
        fundSize: 5600000000,
        fundingStatus: 0.96,
        investmentOptions: [],
        websiteUrl: 'https://www.provident10.ca',
        contactInfo: 'Provident10',
        lastUpdated: new Date(),
        sources: ['Provident10 Annual Report']
      },
      {
        name: 'Newfoundland and Labrador Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for NL teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Newfoundland and Labrador',
        sector: 'Education',
        membershipSize: 16000,
        fundSize: 3900000000,
        fundingStatus: 0.97,
        investmentOptions: [],
        websiteUrl: 'https://www.tppcnl.ca',
        contactInfo: 'Teachers\' Pension Plan Corporation',
        lastUpdated: new Date(),
        sources: ['NL Teachers\' Pension Plan Corporation']
      },

      // Territories
      {
        name: 'Northwest Territories Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for NWT public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Northwest Territories',
        sector: 'Public Service',
        membershipSize: 5800,
        fundSize: 1900000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.hr.gov.nt.ca/benefits/pension-plan',
        contactInfo: 'NWT Financial Management Board',
        lastUpdated: new Date(),
        sources: ['Government of Northwest Territories']
      },
      {
        name: 'Yukon Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Yukon public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Yukon',
        sector: 'Public Service',
        membershipSize: 5200,
        fundSize: 1700000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://yukon.ca/en/your-government/jobs-government/pension-plan',
        contactInfo: 'Yukon Public Service Commission',
        lastUpdated: new Date(),
        sources: ['Government of Yukon']
      },
      {
        name: 'Nunavut Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Nunavut public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Nunavut',
        sector: 'Public Service',
        membershipSize: 4500,
        fundSize: 1500000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.gov.nu.ca/human-resources/information/pension-plan',
        contactInfo: 'Nunavut Department of Human Resources',
        lastUpdated: new Date(),
        sources: ['Government of Nunavut']
      },

      // Specialized Provincial Crown Corporation Plans
      {
        name: 'Hydro-Québec Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Hydro-Québec employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: false,
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Energy',
        membershipSize: 21000,
        fundSize: 27500000000,
        fundingStatus: 1.09,
        investmentOptions: [],
        websiteUrl: 'https://www.hydroquebec.com/employees/pension-plan.html',
        contactInfo: 'Hydro-Québec Pension Plan Administration',
        lastUpdated: new Date(),
        sources: ['Hydro-Québec Annual Report']
      },
      {
        name: 'Ontario Power Generation Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for OPG employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Energy',
        membershipSize: 18000,
        fundSize: 19000000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.opg.com/careers/benefits-and-pension',
        contactInfo: 'OPG Pension Services',
        lastUpdated: new Date(),
        sources: ['Ontario Power Generation']
      }
    ];

    const municipalPlans = [
      {
        name: 'Ontario Municipal Employees Retirement System (OMERS)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Ontario municipal employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Municipal',
        membershipSize: 500000,
        fundSize: 110000000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.omers.com',
        contactInfo: 'OMERS Client Services',
        lastUpdated: new Date(),
        sources: ['OMERS Annual Report']
      },
      // Add more municipal plans...
    ];

    const privateSectorPlans = [
      {
        name: 'Bell Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Bell Canada employees',
        accrualRate: 0.0175,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Private',
        membershipSize: 85000,
        fundSize: 25000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.bell.ca/bell-pension-plan',
        contactInfo: 'Bell Pension Services',
        lastUpdated: new Date(),
        sources: ['Bell Canada Annual Report']
      },
    ];

    // Batch insert plans by sector
    for (const planSet of [federalPlans, provincialPlans, municipalPlans, privateSectorPlans]) {
      for (const plan of planSet) {
        try {
          await prisma.pensionPlan.create({
            data: plan
          });
        } catch (error) {
          console.error(`Failed to create plan ${plan.name}:`, error);
          throw error;
        }
      }
    }

    const planCount = await prisma.pensionPlan.count();
    console.log(`Seed completed successfully. Created ${planCount} pension plans.`);

  } catch (error) {
    console.error('Error during seeding:', error);
    throw error;
  }
}

main()
  .catch((e) => {
    console.error('Failed to seed database:', e);
    process.exit(1);
  })
  .finally(async () => {
    console.log('Cleaning up prisma client...');
    await prisma.$disconnect();
  });