import { PrismaClient, PlanType } from '@prisma/client';

const prisma = new PrismaClient({
  log: ['error', 'warn'],
});

async function main() {
  console.log('Starting seed...');

  try {
    console.log('Clearing existing data...');
    await prisma.pensionPlan.deleteMany();

    const federalPlans = [
      // Core Public Service
      {
        name: 'Public Service Pension Plan (PSPP)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for federal public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Public Service',
        membershipSize: 320000,
        fundSize: 170000000000,
        fundingStatus: 1.08,
        investmentOptions: [],
        websiteUrl: 'https://www.canada.ca/en/treasury-board-secretariat/topics/pension-benefits.html',
        contactInfo: 'Government of Canada Pension Centre',
        lastUpdated: new Date(),
        sources: ['Treasury Board of Canada']
      },

      // Military and Defense
      {
        name: 'Canadian Forces Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for regular force members of the Canadian Armed Forces',
        accrualRate: 0.02,
        retirementAge: 60,
        earlyRetirementAge: 50,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Military',
        membershipSize: 95000,
        fundSize: 55000000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.canada.ca/en/department-national-defence/services/benefits-military/pension-benefits.html',
        contactInfo: 'CAF Pension Services',
        lastUpdated: new Date(),
        sources: ['Department of National Defence']
      },
      {
        name: 'Reserve Force Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for members of the Canadian Forces Reserve',
        accrualRate: 0.02,
        retirementAge: 60,
        earlyRetirementAge: 50,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Military',
        membershipSize: 27000,
        fundSize: 750000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.canada.ca/en/department-national-defence/services/benefits-military/pension-benefits/reserve.html',
        contactInfo: 'Reserve Force Pension Services',
        lastUpdated: new Date(),
        sources: ['Department of National Defence']
      },

      // Law Enforcement
      {
        name: 'Royal Canadian Mounted Police Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for members of the RCMP',
        accrualRate: 0.02,
        retirementAge: 60,
        earlyRetirementAge: 50,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Law Enforcement',
        membershipSize: 40000,
        fundSize: 13000000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.rcmp-grc.gc.ca/en/pension-benefits',
        contactInfo: 'RCMP Pension Services',
        lastUpdated: new Date(),
        sources: ['RCMP']
      },

      // Federal Crown Corporations
      {
        name: 'Bank of Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Bank of Canada employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Crown Corporation',
        membershipSize: 4500,
        fundSize: 2000000000,
        fundingStatus: 1.06,
        investmentOptions: [],
        websiteUrl: 'https://www.bankofcanada.ca/careers/pension-benefits/',
        contactInfo: 'Bank of Canada Pension Services',
        lastUpdated: new Date(),
        sources: ['Bank of Canada Annual Report']
      },
      {
        name: 'Canada Post Corporation Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Canada Post employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Crown Corporation',
        membershipSize: 64000,
        fundSize: 27000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.canadapost.ca/cpc/en/our-company/about-us/pension-plan.page',
        contactInfo: 'Canada Post Pension Centre',
        lastUpdated: new Date(),
        sources: ['Canada Post Annual Report']
      },
      {
        name: 'CBC/Radio-Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for CBC/Radio-Canada employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Crown Corporation',
        membershipSize: 8500,
        fundSize: 8000000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.cbc.radio-canada.ca/en/working-with-us/retirement',
        contactInfo: 'CBC Pension Administration Centre',
        lastUpdated: new Date(),
        sources: ['CBC/Radio-Canada Annual Report']
      },
      {
        name: 'VIA Rail Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for VIA Rail employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Crown Corporation',
        membershipSize: 3000,
        fundSize: 2500000000,
        fundingStatus: 0.96,
        investmentOptions: [],
        websiteUrl: 'https://www.viarail.ca/en/about-via-rail/careers/benefits',
        contactInfo: 'VIA Rail Pension Services',
        lastUpdated: new Date(),
        sources: ['VIA Rail Annual Report']
      },

      // Federal Agencies
      {
        name: 'National Research Council Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for NRC employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Research',
        membershipSize: 4200,
        fundSize: 3500000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://nrc.canada.ca/en/careers/benefits',
        contactInfo: 'NRC Pension Services',
        lastUpdated: new Date(),
        sources: ['National Research Council']
      },
      {
        name: 'Canadian Nuclear Laboratories Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for CNL employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Energy',
        membershipSize: 3500,
        fundSize: 3000000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.cnl.ca/careers/benefits/',
        contactInfo: 'CNL Pension Administration',
        lastUpdated: new Date(),
        sources: ['Canadian Nuclear Laboratories']
      }
    ];

    const provincialPlans = [
      {
        name: 'Ontario Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Ontario teachers and education workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Education',
        membershipSize: 330000,
        fundSize: 220000000000,
        fundingStatus: 1.13,
        investmentOptions: [],
        websiteUrl: 'https://www.otpp.com',
        contactInfo: 'OTPP Member Services',
        lastUpdated: new Date(),
        sources: ['OTPP Annual Report']
      },
      {
        name: 'Healthcare of Ontario Pension Plan (HOOPP)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Ontario healthcare workers',
        accrualRate: 0.0175,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Healthcare',
        membershipSize: 400000,
        fundSize: 104000000000,
        fundingStatus: 1.11,
        investmentOptions: [],
        websiteUrl: 'https://hoopp.com',
        contactInfo: 'HOOPP Client Services',
        lastUpdated: new Date(),
        sources: ['HOOPP Annual Report']
      },
      {
        name: 'OPTrust (Ontario Public Service Employees Union Pension Plan)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Ontario public service employees and OPSEU members',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Public Service',
        membershipSize: 95000,
        fundSize: 25000000000,
        fundingStatus: 1.09,
        investmentOptions: [],
        websiteUrl: 'https://www.optrust.com',
        contactInfo: 'OPTrust Member Services',
        lastUpdated: new Date(),
        sources: ['OPTrust Annual Report']
      },
      {
        name: 'Ontario Power Generation Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for OPG employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Energy',
        membershipSize: 18000,
        fundSize: 19000000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.opg.com/careers/benefits-and-pension',
        contactInfo: 'OPG Pension Services',
        lastUpdated: new Date(),
        sources: ['Ontario Power Generation']
      },

      // British Columbia
      {
        name: 'British Columbia Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for BC teachers and education workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'British Columbia',
        sector: 'Education',
        membershipSize: 98000,
        fundSize: 33200000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://tpp.pensionsbc.ca',
        contactInfo: 'Teachers\' Pension Plan',
        lastUpdated: new Date(),
        sources: ['BC Teachers\' Pension Plan']
      },
      {
        name: 'British Columbia Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for BC public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'British Columbia',
        sector: 'Public Service',
        membershipSize: 135000,
        fundSize: 37000000000,
        fundingStatus: 1.07,
        investmentOptions: [],
        websiteUrl: 'https://pspp.pensionsbc.ca',
        contactInfo: 'Public Service Pension Plan of BC',
        lastUpdated: new Date(),
        sources: ['BC Public Service Pension Plan']
      },

      // Quebec
      {
        name: 'RREGOP (Quebec Government and Public Employees Retirement Plan)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Main pension plan for Quebec public sector employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: false, // Quebec has QPP instead
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Public Service',
        membershipSize: 580000,
        fundSize: 76500000000,
        fundingStatus: 1.06,
        investmentOptions: [],
        websiteUrl: 'https://www.retraitequebec.gouv.qc.ca',
        contactInfo: 'Retraite Québec',
        lastUpdated: new Date(),
        sources: ['Retraite Québec']
      },
      {
        name: 'Teachers Pension Plan (Quebec)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Quebec teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: false,
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Education',
        membershipSize: 220000,
        fundSize: 42000000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.retraitequebec.gouv.qc.ca',
        contactInfo: 'Retraite Québec',
        lastUpdated: new Date(),
        sources: ['Retraite Québec']
      },
      {
        name: 'Hydro-Québec Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Hydro-Québec employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: false,
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Energy',
        membershipSize: 21000,
        fundSize: 27500000000,
        fundingStatus: 1.09,
        investmentOptions: [],
        websiteUrl: 'https://www.hydroquebec.com/employees/pension-plan.html',
        contactInfo: 'Hydro-Québec Pension Plan Administration',
        lastUpdated: new Date(),
        sources: ['Hydro-Québec Annual Report']
      },

      // Alberta
      {
        name: 'Alberta Teachers\' Retirement Fund',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Alberta teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Alberta',
        sector: 'Education',
        membershipSize: 84000,
        fundSize: 20500000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.atrf.com',
        contactInfo: 'ATRF Member Services',
        lastUpdated: new Date(),
        sources: ['Alberta Teachers\' Retirement Fund']
      },
      {
        name: 'Local Authorities Pension Plan (Alberta)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Alberta local government and health care employees',
        accrualRate: 0.0185,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Alberta',
        sector: 'Public Service',
        membershipSize: 275000,
        fundSize: 53000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.lapp.ca',
        contactInfo: 'LAPP Member Services',
        lastUpdated: new Date(),
        sources: ['Local Authorities Pension Plan']
      },

      // Nova Scotia
      {
        name: 'Nova Scotia Public Service Superannuation Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Nova Scotia public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Nova Scotia',
        sector: 'Public Service',
        membershipSize: 38000,
        fundSize: 6800000000,
        fundingStatus: 0.98,
        investmentOptions: [],
        websiteUrl: 'https://www.nspssp.ca',
        contactInfo: 'NS Pension Services Corporation',
        lastUpdated: new Date(),
        sources: ['Nova Scotia Pension Services Corporation']
      },
      {
        name: 'Nova Scotia Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Nova Scotia teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Nova Scotia',
        sector: 'Education',
        membershipSize: 32000,
        fundSize: 5200000000,
        fundingStatus: 0.97,
        investmentOptions: [],
        websiteUrl: 'https://www.nstpp.ca',
        contactInfo: 'NS Teachers\' Pension Plan',
        lastUpdated: new Date(),
        sources: ['Nova Scotia Teachers\' Pension Plan']
      },
      {
        name: 'Nova Scotia Power Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Nova Scotia Power employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Nova Scotia',
        sector: 'Energy',
        membershipSize: 3000,
        fundSize: 1400000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.nspower.ca/careers/benefits',
        contactInfo: 'NS Power Pension Services',
        lastUpdated: new Date(),
        sources: ['Nova Scotia Power Annual Report']
      },

      // Manitoba
      {
        name: 'Civil Service Superannuation Plan (Manitoba)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Manitoba public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Manitoba',
        sector: 'Public Service',
        membershipSize: 54000,
        fundSize: 8500000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.cssb.mb.ca',
        contactInfo: 'Civil Service Superannuation Board',
        lastUpdated: new Date(),
        sources: ['Manitoba CSSB']
      },
      {
        name: 'Healthcare Employees Pension Plan - Manitoba',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Manitoba healthcare workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Manitoba',
        sector: 'Healthcare',
        membershipSize: 80000,
        fundSize: 9200000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.hepp.mb.ca',
        contactInfo: 'HEPP Member Services',
        lastUpdated: new Date(),
        sources: ['HEPP Annual Report']
      },

      // Saskatchewan
      {
        name: 'Saskatchewan Healthcare Employees\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Saskatchewan healthcare workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Saskatchewan',
        sector: 'Healthcare',
        membershipSize: 60000,
        fundSize: 8100000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.shepp.ca',
        contactInfo: 'SHEPP Member Services',
        lastUpdated: new Date(),
        sources: ['SHEPP Annual Report']
      },
      {
        name: 'Saskatchewan Teachers\' Retirement Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Saskatchewan teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Saskatchewan',
        sector: 'Education',
        membershipSize: 42000,
        fundSize: 6500000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.stf.sk.ca/pension',
        contactInfo: 'Saskatchewan Teachers\' Federation',
        lastUpdated: new Date(),
        sources: ['Saskatchewan Teachers\' Federation']
      },
      // Saskatchewan (continued)
      {
        name: 'SaskPower Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for SaskPower employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Saskatchewan',
        sector: 'Energy',
        membershipSize: 3200,
        fundSize: 2800000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.saskpower.com/careers/benefits',
        contactInfo: 'SaskPower Pension Services',
        lastUpdated: new Date(),
        sources: ['SaskPower Annual Report']
      },

      // New Brunswick
      {
        name: 'New Brunswick Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for New Brunswick public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'New Brunswick',
        sector: 'Public Service',
        membershipSize: 40000,
        fundSize: 7300000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.vestcor.org/nbpspp',
        contactInfo: 'Vestcor Pension Services',
        lastUpdated: new Date(),
        sources: ['Vestcor Annual Report']
      },
      {
        name: 'New Brunswick Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for New Brunswick teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'New Brunswick',
        sector: 'Education',
        membershipSize: 20000,
        fundSize: 6100000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.vestcor.org/nbtpp',
        contactInfo: 'Vestcor Pension Services',
        lastUpdated: new Date(),
        sources: ['Vestcor Annual Report']
      },
      {
        name: 'NB Power Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for New Brunswick Power employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'New Brunswick',
        sector: 'Energy',
        membershipSize: 2500,
        fundSize: 1200000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.nbpower.com/careers/benefits',
        contactInfo: 'NB Power Pension Services',
        lastUpdated: new Date(),
        sources: ['NB Power Annual Report']
      },

      // Prince Edward Island
      {
        name: 'Prince Edward Island Civil Service Superannuation Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for PEI public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Prince Edward Island',
        sector: 'Public Service',
        membershipSize: 8000,
        fundSize: 1800000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.peicssf.ca',
        contactInfo: 'PEI Civil Service Superannuation Fund',
        lastUpdated: new Date(),
        sources: ['PEI Public Sector Pensions']
      },
      {
        name: 'Prince Edward Island Teachers\' Superannuation Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for PEI teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Prince Edward Island',
        sector: 'Education',
        membershipSize: 3500,
        fundSize: 950000000,
        fundingStatus: 0.99,
        investmentOptions: [],
        websiteUrl: 'https://www.peitpp.ca',
        contactInfo: 'PEI Teachers\' Superannuation Commission',
        lastUpdated: new Date(),
        sources: ['PEI Teachers\' Federation']
      },

      // Newfoundland and Labrador
      {
        name: 'Newfoundland and Labrador Public Service Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for NL public service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Newfoundland and Labrador',
        sector: 'Public Service',
        membershipSize: 27000,
        fundSize: 5600000000,
        fundingStatus: 0.96,
        investmentOptions: [],
        websiteUrl: 'https://www.provident10.ca',
        contactInfo: 'Provident10',
        lastUpdated: new Date(),
        sources: ['Provident10 Annual Report']
      },
      {
        name: 'Newfoundland and Labrador Teachers\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for NL teachers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Newfoundland and Labrador',
        sector: 'Education',
        membershipSize: 16000,
        fundSize: 3900000000,
        fundingStatus: 0.97,
        investmentOptions: [],
        websiteUrl: 'https://www.tppcnl.ca',
        contactInfo: 'Teachers\' Pension Plan Corporation',
        lastUpdated: new Date(),
        sources: ['NL Teachers\' Pension Plan Corporation']
      }
    ];

    const municipalPlans = [
      // Ontario
      {
        name: 'Ontario Municipal Employees Retirement System (OMERS)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Multi-employer pension plan for Ontario municipal employees, including city workers, police, firefighters, and transit workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Municipal',
        membershipSize: 500000,
        fundSize: 110000000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.omers.com',
        contactInfo: 'OMERS Client Services',
        lastUpdated: new Date(),
        sources: ['OMERS Annual Report']
      },

      // British Columbia
      {
        name: 'Municipal Pension Plan of British Columbia',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for BC municipal employees, including city workers, firefighters, police, and transit workers',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'British Columbia',
        sector: 'Municipal',
        membershipSize: 205000,
        fundSize: 45000000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://mpp.pensionsbc.ca',
        contactInfo: 'Municipal Pension Plan of BC',
        lastUpdated: new Date(),
        sources: ['BC Municipal Pension Plan']
      },

      // Alberta
      {
        name: 'Special Forces Pension Plan (Alberta)',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for police officers in major Alberta municipalities',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Alberta',
        sector: 'Municipal',
        membershipSize: 7500,
        fundSize: 3200000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.sfpp.ca',
        contactInfo: 'SFPP Member Services',
        lastUpdated: new Date(),
        sources: ['Special Forces Pension Plan']
      },

      // Quebec
      {
        name: 'Régime de Retraite des Employés Municipaux du Québec',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Quebec municipal employees pension plan',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: false,
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Municipal',
        membershipSize: 150000,
        fundSize: 25000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.retraitequebec.gouv.qc.ca',
        contactInfo: 'Retraite Québec',
        lastUpdated: new Date(),
        sources: ['Retraite Québec']
      },

      // Individual City Plans
      {
        name: 'City of Montreal Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for City of Montreal employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: false,
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Municipal',
        membershipSize: 45000,
        fundSize: 8500000000,
        fundingStatus: 0.98,
        investmentOptions: [],
        websiteUrl: 'https://montreal.ca/sujets/regime-de-retraite',
        contactInfo: 'Montreal Pension Services',
        lastUpdated: new Date(),
        sources: ['City of Montreal']
      },
      {
        name: 'City of Winnipeg Employee Benefits Program',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for City of Winnipeg employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Manitoba',
        sector: 'Municipal',
        membershipSize: 17000,
        fundSize: 5200000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.winnipeg.ca/hr/pension/default.stm',
        contactInfo: 'Winnipeg Pension Services',
        lastUpdated: new Date(),
        sources: ['City of Winnipeg']
      },
      {
        name: 'City of Regina Civic Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for City of Regina employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Saskatchewan',
        sector: 'Municipal',
        membershipSize: 7000,
        fundSize: 1800000000,
        fundingStatus: 0.97,
        investmentOptions: [],
        websiteUrl: 'https://www.regina.ca/city-government/jobs/benefits/',
        contactInfo: 'Regina Pension Services',
        lastUpdated: new Date(),
        sources: ['City of Regina']
      },
      {
        name: 'Halifax Regional Municipality Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Halifax municipal employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Nova Scotia',
        sector: 'Municipal',
        membershipSize: 9000,
        fundSize: 2400000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.hrmpension.ca',
        contactInfo: 'HRM Pension Plan Office',
        lastUpdated: new Date(),
        sources: ['Halifax Regional Municipality Pension Plan']
      },
      {
        name: 'Canadian National Railway Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for CN Rail employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Transportation',
        membershipSize: 50000,
        fundSize: 19000000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.cn.ca/en/careers/benefits/',
        contactInfo: 'CN Pension Services',
        lastUpdated: new Date(),
        sources: ['CN Annual Report']
      },
      {
        name: 'Canadian Pacific Railway Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for CP Rail employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Transportation',
        membershipSize: 35000,
        fundSize: 15000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.cpr.ca/en/careers/benefits',
        contactInfo: 'CP Pension Services',
        lastUpdated: new Date(),
        sources: ['CP Rail Annual Report']
      },

      // Financial Sector
      {
        name: 'Royal Bank of Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for RBC employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Financial',
        membershipSize: 65000,
        fundSize: 14500000000,
        fundingStatus: 1.07,
        investmentOptions: [],
        websiteUrl: 'https://www.rbc.com/careers/benefits.html',
        contactInfo: 'RBC Pension Services',
        lastUpdated: new Date(),
        sources: ['RBC Annual Report']
      },
      {
        name: 'Bank of Montreal Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for BMO employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Financial',
        membershipSize: 45000,
        fundSize: 12000000000,
        fundingStatus: 1.06,
        investmentOptions: [],
        websiteUrl: 'https://www.bmo.com/careers/benefits',
        contactInfo: 'BMO Pension Services',
        lastUpdated: new Date(),
        sources: ['BMO Annual Report']
      },

      // Telecommunications
      {
        name: 'Telus Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Telus employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Telecommunications',
        membershipSize: 27000,
        fundSize: 9800000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.telus.com/careers/benefits',
        contactInfo: 'Telus Pension Services',
        lastUpdated: new Date(),
        sources: ['Telus Annual Report']
      },

      // Insurance Sector
      {
        name: 'Manulife Employee Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Manulife employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Insurance',
        membershipSize: 35000,
        fundSize: 11000000000,
        fundingStatus: 1.08,
        investmentOptions: [],
        websiteUrl: 'https://www.manulife.ca/careers/benefits.html',
        contactInfo: 'Manulife Pension Services',
        lastUpdated: new Date(),
        sources: ['Manulife Annual Report']
      },

      // Energy Sector
      {
        name: 'Enbridge Employee Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Enbridge employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Energy',
        membershipSize: 12000,
        fundSize: 5500000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.enbridge.com/careers/benefits',
        contactInfo: 'Enbridge Pension Services',
        lastUpdated: new Date(),
        sources: ['Enbridge Annual Report']
      },
      {
        name: 'SaskPower Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for SaskPower employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Saskatchewan',
        sector: 'Energy',
        membershipSize: 3200,
        fundSize: 2800000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.saskpower.com/careers/benefits',
        contactInfo: 'SaskPower Pension Services',
        lastUpdated: new Date(),
        sources: ['SaskPower Annual Report']
      },

      // Union Plans
      {
        name: 'CUPE Employees\' Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for employees of CUPE union',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Union',
        membershipSize: 6000,
        fundSize: 2500000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.cupe.ca/pensions',
        contactInfo: 'CUPE Pension Administration',
        lastUpdated: new Date(),
        sources: ['CUPE Annual Report']
      },
      // Additional Financial Sector
      {
        name: 'TD Bank Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for TD Bank employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Financial',
        membershipSize: 55000,
        fundSize: 13500000000,
        fundingStatus: 1.06,
        investmentOptions: [],
        websiteUrl: 'https://www.td.com/careers/benefits',
        contactInfo: 'TD Pension Services',
        lastUpdated: new Date(),
        sources: ['TD Bank Annual Report']
      },
      {
        name: 'Scotiabank Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Scotiabank employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Financial',
        membershipSize: 50000,
        fundSize: 12800000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.scotiabank.com/careers/benefits',
        contactInfo: 'Scotiabank Pension Services',
        lastUpdated: new Date(),
        sources: ['Scotiabank Annual Report']
      },
      {
        name: 'CIBC Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for CIBC employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Financial',
        membershipSize: 45000,
        fundSize: 11500000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.cibc.com/careers/benefits',
        contactInfo: 'CIBC Pension Services',
        lastUpdated: new Date(),
        sources: ['CIBC Annual Report']
      },

      // Additional Insurance Sector
      {
        name: 'Sun Life Financial Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Sun Life employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Insurance',
        membershipSize: 30000,
        fundSize: 10200000000,
        fundingStatus: 1.07,
        investmentOptions: [],
        websiteUrl: 'https://www.sunlife.ca/careers/benefits',
        contactInfo: 'Sun Life Pension Services',
        lastUpdated: new Date(),
        sources: ['Sun Life Annual Report']
      },
      {
        name: 'Canada Life Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Canada Life employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Insurance',
        membershipSize: 25000,
        fundSize: 9500000000,
        fundingStatus: 1.06,
        investmentOptions: [],
        websiteUrl: 'https://www.canadalife.com/careers/benefits',
        contactInfo: 'Canada Life Pension Services',
        lastUpdated: new Date(),
        sources: ['Canada Life Annual Report']
      },

      // Additional Telecommunications
      {
        name: 'Bell Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Bell Canada employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Telecommunications',
        membershipSize: 85000,
        fundSize: 25000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.bell.ca/careers/benefits',
        contactInfo: 'Bell Pension Services',
        lastUpdated: new Date(),
        sources: ['Bell Canada Annual Report']
      },
      {
        name: 'Rogers Communications Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Rogers employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Telecommunications',
        membershipSize: 30000,
        fundSize: 8500000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.rogers.com/careers/benefits',
        contactInfo: 'Rogers Pension Services',
        lastUpdated: new Date(),
        sources: ['Rogers Annual Report']
      },

      // More Energy Sector
      {
        name: 'TransCanada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for TC Energy employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Energy',
        membershipSize: 7500,
        fundSize: 4200000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.tcenergy.com/careers/benefits',
        contactInfo: 'TC Energy Pension Services',
        lastUpdated: new Date(),
        sources: ['TC Energy Annual Report']
      },
      {
        name: 'Manitoba Hydro Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Manitoba Hydro employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Manitoba',
        sector: 'Energy',
        membershipSize: 6000,
        fundSize: 3800000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.hydro.mb.ca/careers/benefits',
        contactInfo: 'Manitoba Hydro Pension Services',
        lastUpdated: new Date(),
        sources: ['Manitoba Hydro Annual Report']
      },

      // More Union Plans
      {
        name: 'UNIFOR Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for UNIFOR union employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Union',
        membershipSize: 8000,
        fundSize: 3200000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.unifor.org/benefits',
        contactInfo: 'UNIFOR Pension Administration',
        lastUpdated: new Date(),
        sources: ['UNIFOR Annual Report']
      },
      {
        name: 'United Food and Commercial Workers Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for UFCW union employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Union',
        membershipSize: 7500,
        fundSize: 2900000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.ufcw.ca/benefits',
        contactInfo: 'UFCW Pension Administration',
        lastUpdated: new Date(),
        sources: ['UFCW Annual Report']
      },
      {
        name: 'Air Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Air Canada employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Aviation',
        membershipSize: 33000,
        fundSize: 21500000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.aircanada.com/careers/benefits',
        contactInfo: 'Air Canada Pension Services',
        lastUpdated: new Date(),
        sources: ['Air Canada Annual Report']
      },
      {
        name: 'NAV CANADA Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for air navigation service employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Aviation',
        membershipSize: 4500,
        fundSize: 6800000000,
        fundingStatus: 1.04,
        investmentOptions: [],
        websiteUrl: 'https://www.navcanada.ca/careers/benefits',
        contactInfo: 'NAV CANADA Pension Services',
        lastUpdated: new Date(),
        sources: ['NAV CANADA Annual Report']
      },

      // Transit Authorities
      {
        name: 'Toronto Transit Commission Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for TTC employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Ontario',
        sector: 'Transit',
        membershipSize: 16000,
        fundSize: 7200000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.ttc.ca/jobs/benefits',
        contactInfo: 'TTC Pension Services',
        lastUpdated: new Date(),
        sources: ['TTC Annual Report']
      },
      {
        name: 'TransLink Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Metro Vancouver transit employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'British Columbia',
        sector: 'Transit',
        membershipSize: 8500,
        fundSize: 2800000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.translink.ca/careers/benefits',
        contactInfo: 'TransLink Pension Services',
        lastUpdated: new Date(),
        sources: ['TransLink Annual Report']
      },

      // Port Authorities
      {
        name: 'Port of Vancouver Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Port of Vancouver employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Maritime',
        membershipSize: 1500,
        fundSize: 950000000,
        fundingStatus: 1.05,
        investmentOptions: [],
        websiteUrl: 'https://www.portvancouver.com/careers/benefits',
        contactInfo: 'Port of Vancouver Pension Services',
        lastUpdated: new Date(),
        sources: ['Port of Vancouver Annual Report']
      },

      // Manufacturing Sector
      {
        name: 'Bombardier Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Bombardier employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Quebec',
        sector: 'Manufacturing',
        membershipSize: 25000,
        fundSize: 8900000000,
        fundingStatus: 0.98,
        investmentOptions: [],
        websiteUrl: 'https://www.bombardier.com/careers/benefits',
        contactInfo: 'Bombardier Pension Services',
        lastUpdated: new Date(),
        sources: ['Bombardier Annual Report']
      },

      // More Provincial Crown Corporations
      {
        name: 'Nova Scotia Power Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for Nova Scotia Power employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Nova Scotia',
        sector: 'Energy',
        membershipSize: 3000,
        fundSize: 1400000000,
        fundingStatus: 1.01,
        investmentOptions: [],
        websiteUrl: 'https://www.nspower.ca/careers/benefits',
        contactInfo: 'NS Power Pension Services',
        lastUpdated: new Date(),
        sources: ['Nova Scotia Power Annual Report']
      },
      {
        name: 'NB Power Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Pension plan for New Brunswick Power employees',
        accrualRate: 0.02,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'New Brunswick',
        sector: 'Energy',
        membershipSize: 2500,
        fundSize: 1200000000,
        fundingStatus: 1.02,
        investmentOptions: [],
        websiteUrl: 'https://www.nbpower.com/careers/benefits',
        contactInfo: 'NB Power Pension Services',
        lastUpdated: new Date(),
        sources: ['NB Power Annual Report']
      }
    ];

    const privateSectorPlans = [
      {
        name: 'Bell Canada Pension Plan',
        type: PlanType.DEFINED_BENEFIT,
        description: 'Primary pension plan for Bell Canada employees',
        accrualRate: 0.0175,
        retirementAge: 65,
        earlyRetirementAge: 55,
        bridgeBenefit: true,
        cppIntegration: true,
        vestingPeriodYears: 2,
        jurisdiction: 'Federal',
        sector: 'Private',
        membershipSize: 85000,
        fundSize: 25000000000,
        fundingStatus: 1.03,
        investmentOptions: [],
        websiteUrl: 'https://www.bell.ca/bell-pension-plan',
        contactInfo: 'Bell Pension Services',
        lastUpdated: new Date(),
        sources: ['Bell Canada Annual Report']
      },
    ];

    // Batch insert plans by sector
    for (const planSet of [federalPlans, provincialPlans, municipalPlans, privateSectorPlans]) {
      for (const plan of planSet) {
        try {
          await prisma.pensionPlan.create({
            data: plan
          });
        } catch (error) {
          console.error(`Failed to create plan ${plan.name}:`, error);
          throw error;
        }
      }
    }

    const planCount = await prisma.pensionPlan.count();
    console.log(`Seed completed successfully. Created ${planCount} pension plans.`);

  } catch (error) {
    console.error('Error during seeding:', error);
    throw error;
  }
}

main()
  .catch((e) => {
    console.error('Failed to seed database:', e);
    process.exit(1);
  })
  .finally(async () => {
    console.log('Cleaning up prisma client...');
    await prisma.$disconnect();
  });