name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch
  
  # Allow manual triggering
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Make sure to set this in repo secrets
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
  DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Project
        run: npm run build

      - name: Export Static Files
        run: npm run export

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: out       # The folder the action should deploy
          clean: true      # Automatically remove deleted files from the deployment